### ISSUE TITLE
request: get avatar for github names

### ISSUE THREAD

**Issue by gauteh** [astroidmail/astroid-plugin-avatar#1]
It would be great if you could somehow deduce the avatar for a github username like it appears in the github comments.

**Comment by emdete** [comment]
the API allows this. problem is: the email must be public and it must be the one the user normally is using (which both is not true for myself). furthermore 2 requests are needed to retrieve the username by email and the avatar:

https://api.github.com/search/users\?q=eg@gaute.vetsj.com+in:email

shows the url which is:

![](https://avatars.githubusercontent.com/u/56827?v=3)

**Comment by gauteh** [comment]
If the plugin has access to the e-mail source it could use the
X-GitHub-Sender header to get the username, and then: 

```
http://stackoverflow.com/questions/22932422/get-github-avatar-from-email-or-name
```

to get the avatar, e.g.:

```
https://github.com/gauteh.png
```

is it worth it? Passing the GMimeObject of the current message is not hard.

Two requests are probably not so good as things are lagging sometimes 
already by uncached avatars.

-gaute

**Comment by emdete** [comment]
i found the .png solution as well but it's two request as well. the .png url responses with an redir to the url which is the one i am detecting. yes, the headerfields would be good to have as one could check if its a github email at all.

don't know if its worse it, avatars are really eye-candy ;)

**Comment by gauteh** [comment]
Check the pull request, it is already implemented.

Den fredag 1. juli 2016 skrev M. Dietrich notifications@github.com
følgende:
